#!/bin/bash
if [ "$1" == "-h" ]; then
  echo "Usage: cv_create [name of new workspace] [path to a utils folder to be copied]"
  exit 0
fi

dst_dir=$1
if [ -d $dst_dir ];  then
  echo "Directory $1 existed, please check it or remove it"
  exit 0
fi

mkdir $dst_dir
cd $dst_dir

mkdir src build test utils docu
touch README.md

touch CMakeLists.txt
echo "project ()
cmake_minimum_required(VERSION 3.0)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_FLAGS -Wall -Wextra )
set(CMAKE_CXX_FLAGS  -g)


find_package(OpenCV 3.2.0 REQUIRED)


MESSAGE ( STATUS \"OpenCV library status:\" )
MESSAGE ( STATUS \"version \${OpenCV_VERSION}\" )
MESSAGE ( STATUS \"libraries \${OpenCV_LIBS}\" )
MESSAGE ( STATUS \"include path \${OpenCV_INCLUDE_DIRS}\" ) 
include_directories(\${OpenCV_INCLUDE_DIRS})
include_directories(\${CMAKE_SOURCE_DIR}/src)
include_directories(\${CMAKE_SOURCE_DIR}/utils)

add_subdirectory(utils)
add_subdirectory(src)
add_subdirectory(test)" >CMakeLists.txt

touch test/CMakeLists.txt
echo "#add_executable()
#target_link_libraries()" > test/CMakeLists.txt


touch src/CMakeLists.txt
echo "#add_library()
#target_link_libraries()" > src/CMakeLists.txt

if [ $# -eq 2 ]
  then
  cd ..
  utils_backup_path=$2
  cp -r $utils_backup_path\/utils/ $dst_dir/
fi

echo "workspace already configurated!"
